### ISSUE TITLE
Revisit the thumnail idea for the carousel - potential test prototype

### ISSUE THREAD

**Issue by busbus** [Esri/photo-survey#12]
Need to update current app images  - 

1. PNG for "heart" icon
2. Enlarge L/R arrows for carousel
3. Remove drop-shadow
4. Improve image hints (...) by changing them from a circle to a square

**Comment by MikeTschudi** [comment]
1,3,4 added via commit b2f96bf4d51bdefc90e7c76691ee8a99f97f385b

**Comment by busbus** [comment]
good to do - works nicely
