### ISSUE TITLE
Carousel - Photo ordering

### ISSUE THREAD

**Issue by busbus** [Esri/photo-survey#13]
Need to reverse the order of the photos (since cameras are orientated starboard and port) one set is reversed.

Data processing tools now mark the appropriate properties REVERSE = YES.

Feature Service (with scrubbed non-associated properties)

http://arcgis4localgov2.maps.arcgis.com/home/item.html?id=7514002e8f584749a1377b123dca3da7

Webmap:

http://arcgis4localgov2.maps.arcgis.com/home/webmap/viewer.html?webmap=252613b18fff42928e6f5ab84edfbaed

**Comment by MikeTschudi** [comment]
Added via commit b54ae36df389063ba915534a9011a805292ba94c

**Comment by busbus** [comment]
Verified Fixed
