### ISSUE TITLE
Allow anonymous login - by option

### ISSUE THREAD

**Issue by busbus** [Esri/photo-survey#20]
Allow anonymous access by configuration - not a default option.

**Comment by MikeTschudi** [comment]
Guest login via commit 590175e6baf1942438ef70ea85c1ceada4383f05

**Comment by busbus** [comment]
Guest (anonymous access) should mark surveyor = 'guest' so that we can submit surveys.  The submit button should be active when the feature service doesn't have editing capabilities i.e. Apply Edits and Update Features is not available.

**Comment by MikeTschudi** [comment]
Guest submission via commit 8ec2d89eec4f90e7584328d05922f8f7bb75ddf5

**Comment by MikeTschudi** [comment]
cf #30 for ArcGIS.com access part of original issue
