### ISSUE TITLE
Enhancement Request : Free Form input for text and numeric fields

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/photo-survey#29]
Allow user to manually type in a value, such as number of attachments, pole height, etc.

**Comment by busbus** [comment]
Mike T - did we ever implement free-form?

**Comment by lindsayking** [comment]
* For number inputs, the tag in the popup should be {number}.
* For text inputs, the tag in the popup should be {text}.

**Comment by MikeTschudi** [comment]
Updated via a0faf7dcfa1e980aeeb3188fa6850933b9100db6 to encode text content before sending to server

**Comment by lindsayking** [comment]
Verified for the June release.
