### ISSUE TITLE
Make it clearer when a survey is in read-only mode

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/photo-survey#33]
If the underlying feature layer cannot be updated, or if the visitor signs in using Guest mode and Guests are not configured to submit surveys, the app disables the submit button, but the disable is subtle and--worse--the visitor might have completed filling out a very long form before he/she gets down to the submit button's location, only to find out that it doesn't work.

Possible improvements:
1. Popup message after signing in in this state to tell the user that submissions will not be possible--it's only for looking at.
2. Gray the survey form or otherwise indicate that it's read-only.

Changes to the submit button, such as making it more obviously disabled, or providing a tooltip saying that the form is read-only (except not for touch devices), or hiding it, are too late in the UI to avoid frustration.

Found by and improvement suggestions by @HeatherEisan and @lindsayking

**Comment by busbus** [comment]
Verified
