### ISSUE TITLE
Load Photos Tool Text Edit

### ISSUE THREAD

**Issue by DeborahRoth** [Esri/photo-survey#39]
@busbus 
Update the help text for the Staging Geodatabase in the Load Photos too. The text currently says, "where you will to store your photo". 

Please remove the word 'to' so that the text reads, "where you will store your photo". 

![loadphotostextedit](https://cloud.githubusercontent.com/assets/12927140/9639815/20ff1dc4-516b-11e5-9f33-b8ec1a71a06e.PNG)

**Comment by busbus** [comment]
Another great catch Deborah!

**Comment by busbus** [comment]
Closed - changed tool completely for next release
