### ISSUE TITLE
Incorrect app reference in 'get started'

### ISSUE THREAD

**Issue by DeborahRoth** [Esri/photo-survey#40]
@busbus 
There is an incorrect app reference on the Photo Survey > Get Started > Publish Application page.

Step 8 references 'Park Locator' instead of 'Photo Survey'.

![wrongappreference](https://cloud.githubusercontent.com/assets/12927140/9639931/dce89f38-516b-11e5-9556-23c8417acdda.PNG)

**Comment by busbus** [comment]
Great catch - thanks Deborah!

**Comment by busbus** [comment]
Fixed with the Oct. 22nd. release of the solutions site
