### ISSUE TITLE
Enhancement Request : Add inset map (display current location of surveyed property)

### ISSUE THREAD

**Issue by ChrisBuscaglia** [Esri/photo-survey#48]
Add inset map, maybe leaflet to show current survey location and whatever basemap you'd like to configure.  This should be a collapsible map that can be moved off view,

**Comment by ChrisBuscaglia** [comment]
Possibly a leaflet map inset - configurable.

**Comment by MikeTschudi** [comment]
‘develop’ branch contains the following overview map configuration options in configuration.json:

* includeOverviewMap: master switch controlling existence of overview map; current value: `true`
* overviewMapInitiallyOpen: switch indicating if overview map is in expanded form upon login; current value: `false`, meaning that it is collapsed
* overviewMapBasemap: overview map's basemap; value is keyword from the list provided under the "Basemaps" heading on this [page](http://esri.github.io/esri-leaflet/api-reference/layers/basemap-layer.html); current value: `"Streets"`
* overviewMapZoom: map zoom level to use when jumping to photo location; current value: `16`,

repository's [demo page](http://esri.github.io/photo-survey/) has a snapshot of 'develop'

**Comment by ChrisBuscaglia** [comment]
Looks good to go.

**Comment by ChrisBuscaglia** [comment]
Re-opening issue.  It seems that zooming out on the inset map will not keep the "X" centered on the photo  location, instead it will float around on the map.
