### ISSUE TITLE
Enhancement idea: clear required-question highlighting when question is answered

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/photo-survey#50]
If a required question is not answered, the question is highlighted:
![image](https://cloud.githubusercontent.com/assets/2125181/12276637/b732f7a2-b92b-11e5-96e7-91fc1d3e54a8.png)

This highlighting persists even after the question is subsequently answered:
![image](https://cloud.githubusercontent.com/assets/2125181/12276649/c5c05378-b92b-11e5-87bb-48b0744badf1.png)

Clearing the highlighting once the question is answered would reinforce the behavior.

**Comment by lindsayking** [comment]
@ChrisBuscaglia @MikeTschudi  -  This enhancement hasn't been implemented for June.  Should I move to future milestone?

**Comment by lindsayking** [comment]
Verified.
