### ISSUE TITLE
Strip out PATH field for "Associate photo with point" option

### ISSUE THREAD

**Issue by lindsayking** [Esri/photo-survey#51]
If the Load Photos tool is run with the "Associate photo with point" option, the PATH field is populated with the path to the photo on disk.  This field should be stripped out before the tool completes.

Related, if the feature service contains a PATH field with path values, the application should still work and users should still be able to successfully submit surveys.

**Comment by ChrisBuscaglia** [comment]
Fixed with the June release, please confirm

**Comment by lindsayking** [comment]
Confirmed.
