### ISSUE TITLE
Add support for displaying images on the survey panel

### ISSUE THREAD

**Issue by lindsayking** [Esri/photo-survey#54]
We would like to display images on the survey panel.  These could be diagrams or sample images that help assist users when filling out a survey.  Rough example below.

![image](https://cloud.githubusercontent.com/assets/4316336/14264342/620b42f4-fa74-11e5-9464-73d148a4b170.png)

Images may be
* associated with potential answers (like the example above, extremely likely for wildlife identification workflows)
* associated with questions themselves, such as a diagram providing helpful information for answering the question  (static image on the survey panel)

When the user clicks on an image in the survey panel, the image should expand to display a full size version.

**Comment by ChrisBuscaglia** [comment]
@MikeTschudi @lindsayking We need to find some time to go over this requirement, will need a design/approach.

**Comment by lindsayking** [comment]
This would involve having an image tag in the popup configuration associated with a url to the image.

**Comment by lindsayking** [comment]
We would like to take the following approach.  This is based off of the experimentation that @MikeTschudi did this week.

The application should support reading an image from a URL inside an {image} tag in the popup configuration.  This {image} tag can either come before or after the tag indicating the answer type.  If before, the image should display above the answer.  If after, it should display below the answer.

Popup configuration example:
<code>Number: {Heading} {image=http://tryitlive.arcgis.com/TaxParcelViewer/images/logo.png} {number}</code>
<code>Text: {SlideName} {text} {image=http://tryitlive.arcgis.com/TaxParcelViewer/images/logo.png}</code>

Result:
![image](https://cloud.githubusercontent.com/assets/4316336/15162662/0799247e-16b9-11e6-97da-b4623d841f1c.png)

**Comment by lindsayking** [comment]
@MikeTschudi @ChrisBuscaglia 

Tested with adding image tags both before and after the answer in the popup configuration for these answer types: button, text, number and dropdown.  In all cases, the image displayed as I would expected it to in relation to the answer on the survey panel.

**Comment by lindsayking** [comment]
Closing this issue - images associated with questions are working as expected.

Have opened a separate issue (#59) for associating images with responses.
