### ISSUE TITLE
App is updating geometry of survey points

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/photo-survey#60]
It is not necessary for the app to update the survey points, and since it is asking the server for the lat/long of the property so that it can display the property location in the overview map, this update is breaking survey point locations if those locations are not also in lat/long.

**Comment by ChrisBuscaglia** [comment]
Looks like this is addressed

**Comment by lindsayking** [comment]
Confirmed in Wildlife Survey.  Points are not moving after surveys are submitted.
