### ISSUE TITLE
Update processing tools to provide longer BESTPHOTOID field

### ISSUE THREAD

**Issue by ChrisBuscaglia** [Esri/photo-survey#65]
If you hit the best photo icon in the web app and then tried to submit the survey, the survey wouldn't submit on a long attachment ID.

Fix was to lengthen the field to 25.

**Comment by cosbyr** [comment]
Need to add the updated Python script with the fix to the final release zip for the website

**Comment by ChrisBuscaglia** [comment]
fixed
