### ISSUE TITLE
Update processing tools to create new survey question format and automated webmap creation

### ISSUE THREAD

**Issue by ChrisBuscaglia** [Esri/photo-survey#74]
- [x] Append process to create new question table
- Option to select a template question table for Wildlife, Property Condition, or Damage Assessment?
- Option for selecting a blank template question table?
- Enforce that all questions must have a domain? 
- [x] Update existing process to remove NULLABLE or NON_NULLABLE as a data requirement
- [x] Auto-create webmap in organization (with Folder)
- Folder Name Option in GP Tools?
- [x] Deprecate ArcMap tools?
- [x] Create survey question template geodatabases
- Images for template questions?
- [x] Publishing the question table service
- Needs to have add, update, and delete features capabilities
- [x] Publishing the photo points feature service
- [x] Generate feedback for photos that are not geolocated with EXIF
- [x] Photo rotation?

**Comment by jessnoo** [comment]
from Nov 1 testing recommendation: when the Load Photos tool is running in Pro, create a map in the project that contains the feature class and table as a part of the process.  could include metadata, symbols, pop ups, etc.  the user can then publish that map as a web map in their org as the next step in the process.

**Comment by cosbyr** [comment]
@ChrisBuscaglia I'm closing this issue. Most of this stuff is outdated or has already been taken care of.
