### ISSUE TITLE
GP tool parameters should be mixed case

### ISSUE THREAD

**Issue by HeatherEisan** [Esri/photo-survey#75]
Looks like mixed case is used for all GP tool parameters. In the Load Photos GP tool the following parameters are combination mixed and lowercase. The whole parameter should be mixed case.

- Select a workflow should be Select a Workflow
- Passenger side photos should be Passenger Side Photos
- Driver side photos should be Driver Side Photos
- Camera supports direction (orientation) should be Camera Supports Direction (Orientation)

**Comment by ChrisBuscaglia** [comment]
@HeatherEisan will update with the next commit

**Comment by ChrisBuscaglia** [comment]
11a6136

**Comment by ChrisBuscaglia** [comment]
@HeatherEisan this also has doc. considerations with updated screenshots, let me know what the best way to handle that would be...we have to update the YAML for the TOC and add the upgrade topic, this could be part of those updates.

**Comment by HeatherEisan** [comment]
@ChrisBuscaglia: I can add doc changes to the Photo Survey doc enhancements [GitHub issue](https://github.com/ArcGIS/arcgis-solutions-website/issues/5806).
