### ISSUE TITLE
GeoDatabase parameter should be mixed case

### ISSUE THREAD

**Issue by HeatherEisan** [Esri/photo-survey#76]
GeoDatabase parameter in the Load Photos GP tool should be Geodatabase.

**Comment by ChrisBuscaglia** [comment]
@HeatherEisan will update with the next commit

**Comment by ChrisBuscaglia** [comment]
11a6136

**Comment by ChrisBuscaglia** [comment]
@HeatherEisan this also has doc. considerations with updated screenshots, let me know what the best way to handle that would be...we have to update the YAML for the TOC and add the upgrade topic, this could be part of those updates.

**Comment by HeatherEisan** [comment]
@ChrisBuscaglia: I can add doc changes to the Photo Survey doc enhancements [GitHub issue](https://github.com/ArcGIS/arcgis-solutions-website/issues/5806).
