### ISSUE TITLE
Document type of geodatabase to create

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/photo-survey#77]
Under the "Publish photo collection" step in both the LG & SG versions, the first step is to "Create a geodatabase to stage your photo collection.", and it includes a link to an overview of creating geodatabases. The overview lists three ways to create a geodatabase--which one should we choose?

**Comment by ChrisBuscaglia** [comment]
Thanks Mike, we don't get into the grit of the type of GDB and not sure that we should, I'll talk to Heather about that. Definitely limitations with SQL Server Express and PGDB.

**Comment by MikeTschudi** [comment]
My main problem was that I had wondered if I should clone the template gdbs or if I should create a new one. Since it's called a staging gdb, is it meant to be temporary? Just need some clarification about how the pieces work together.
