### ISSUE TITLE
Tool in develop branch can't be opened in ArcMap 10.5.1

### ISSUE THREAD

**Issue by chris-fox** [Esri/photo-survey#78]
I attempted to open the Load Photos tool in 10.5.1, but when i expanded to toolbox there was no tool. I opened the toolbox in Pro and saved it as a 10.3 version of the toolbox and then I was able to successfully open and run the tool in 10.3 and 10.5.1.

**Comment by ChrisBuscaglia** [comment]
@chris-fox thanks - I think that @MikeTschudi has the same issue.  I'll commit a change this evening.

**Comment by ChrisBuscaglia** [comment]
@chris-fox I added a 103 toolbox, had issues with changing the name of tooboxes...but will update before we ship.  11a6136
