### ISSUE TITLE
Updating the survey to the database

### ISSUE THREAD

**Issue by kalluris** [Esri/photo-survey#91]
We integrated Cyclomedia Imagery into the photo survey app to use the 360 degree panoramic images instead of the static images on request from a customer but we are having trouble to update the survey to the backend from the UI. Need some help there and also Is there any Plan to update the Photo survey to ARCGIS JS API 4.x we need the Z coordinate which is not possible in the current version using the 3.x API

**Comment by ChrisBuscaglia** [comment]
@MikeTschudi my understanding is that we don't use the ArcGIS API for JS, we do however make calls to our REST API to process surveys, edit features, etc.  We use leaflet for the optional mapping component.

**Comment by MikeTschudi** [comment]
@ChrisBuscaglia that is correct--no ArcGIS API for JS in the app

**Comment by ChrisBuscaglia** [comment]
@kalluris Closing this issue - let us know if you have any other issues.
